/*
 * Ibatis.Net for Data Mapper, and Generated by MyGeneration
 * 
 * NameSpace   : DMS.Model 
 * ClassName   : AopDealerHospitalTemp
 * Created Time: 2014/1/7 15:44:21
 *
 ******* Copyright (C) 2009/2010 - GrapeCity **********
 *
******************************************************/

using System;

namespace DMS.Model
{
    /// <summary>
    ///	AopDealerHospitalTemp
    /// </summary>
    [Serializable]
    public class AopDealerHospitalTemp : BaseModel
    {
        #region Private Members 10

        private Guid _id;
        private Guid _contract_id;
        private Guid _dealer_dma_id;
        private Guid? _dealer_dma_id_actual;
        private Guid _productline_bum_id;
        private Guid _hospital_id;
        private string _year;
        private string _month;
        private double? _amount;
        private Guid? _update_user_id;
        private DateTime? _update_date;
        private Guid? _pct_id;
        private Guid? _cc_id;
        #endregion

        #region Default ( Empty ) Class Constuctor
        /// <summary>
        /// default constructor
        /// </summary>
        public AopDealerHospitalTemp()
        {
            _id = Guid.Empty;
            _contract_id = Guid.Empty;
            _dealer_dma_id = Guid.Empty;
            _dealer_dma_id_actual = null;
            _productline_bum_id = Guid.Empty;
            _hospital_id = Guid.Empty;
            _year = null;
            _month = null;
            _amount = null;
            _update_user_id = null;
            _update_date = null;
            _pct_id = null;
            _cc_id = null;
        }
        #endregion // End of Default ( Empty ) Class Constuctor

        #region Public Properties

        /// <summary>
        /// AOPDH_ID
        /// </summary>		
        public Guid Id
        {
            get { return _id; }
            set { _id = value; }
        }

        /// <summary>
        /// AOPD_Contract_ID
        /// </summary>		
        public Guid ContractId
        {
            get { return _contract_id; }
            set { _contract_id = value; }
        }

        /// <summary>
        /// AOPDH_Dealer_DMA_ID
        /// </summary>		
        public Guid DealerDmaId
        {
            get { return _dealer_dma_id; }
            set { _dealer_dma_id = value; }
        }

        /// <summary>
        /// AOPDH_Dealer_DMA_ID_Actual
        /// </summary>		
        public Guid? DealerDmaIdActual
        {
            get { return _dealer_dma_id_actual; }
            set { _dealer_dma_id_actual = value; }
        }

        /// <summary>
        /// AOPDH_ProductLine_BUM_ID
        /// </summary>		
        public Guid ProductLineBumId
        {
            get { return _productline_bum_id; }
            set { _productline_bum_id = value; }
        }

        /// <summary>
        /// AOPDH_Hospital_ID
        /// </summary>		
        public Guid HospitalId
        {
            get { return _hospital_id; }
            set { _hospital_id = value; }
        }

        /// <summary>
        /// AOPDH_Year
        /// </summary>		
        public string Year
        {
            get { return _year; }
            set
            {
                if (value != null && value.Length > 30)
                    throw new ArgumentOutOfRangeException("Invalid value for Year", value, value.ToString());

                _year = value;
            }
        }

        /// <summary>
        /// AOPDH_Month
        /// </summary>		
        public string Month
        {
            get { return _month; }
            set
            {
                if (value != null && value.Length > 50)
                    throw new ArgumentOutOfRangeException("Invalid value for Month", value, value.ToString());

                _month = value;
            }
        }

        /// <summary>
        /// AOPDH_Amount
        /// </summary>		
        public double? Amount
        {
            get { return _amount; }
            set { _amount = value; }
        }

        /// <summary>
        /// AOPDH_Update_User_ID
        /// </summary>		
        public Guid? UpdateUserId
        {
            get { return _update_user_id; }
            set { _update_user_id = value; }
        }

        /// <summary>
        /// AOPDH_Update_Date
        /// </summary>		
        public DateTime? UpdateDate
        {
            get { return _update_date; }
            set { _update_date = value; }
        }

        public Guid? PctId
        {
            get { return _pct_id; }
            set { _pct_id = value; }
        }
        public Guid? CcId
        {
            get { return _cc_id; }
            set { _cc_id = value; }
        }

        #endregion





    }
}
