/*
 * Ibatis.Net for Data Mapper, and Generated by MyGeneration
 * 
 * NameSpace   : DMS.Model 
 * ClassName   : TrainingSignIn
 * Created Time: 2013/12/10 16:21:45
 *
 ******* Copyright (C) 2009/2010 - GrapeCity **********
 *
******************************************************/

using System;

namespace DMS.Model
{
	/// <summary>
	///	TrainingSignIn
	/// </summary>
	[Serializable]
	public class TrainingSignIn
	{
		#region Private Members 9
		
		private Guid _tsi_id; 
		private Guid _tsi_cm_id; 
		private string _tsi_name; 
		private string _tsi_dealername; 
		private DateTime? _tsi_trainingdate; 
		private DateTime? _bl_create_date; 
		private Guid? _bl_create_user; 
		private DateTime? _bl_update_date; 
		private Guid? _bl_update_user; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public TrainingSignIn()
		{
			_tsi_id = Guid.Empty; 
			_tsi_cm_id = Guid.Empty; 
			_tsi_name = null; 
			_tsi_dealername = null; 
			_tsi_trainingdate = null;
			_bl_create_date = null;
			_bl_create_user = null;
			_bl_update_date = null;
			_bl_update_user = null;
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// TSI_ID
		/// </summary>		
		public Guid TsiId
		{
			get { return _tsi_id; }
			set { _tsi_id = value; }
		}
			
		/// <summary>
		/// 合同ID
		/// </summary>		
		public Guid TsiCmId
		{
			get { return _tsi_cm_id; }
			set { _tsi_cm_id = value; }
		}
			
		/// <summary>
		/// 姓名
		/// </summary>		
		public string TsiName
		{
			get { return _tsi_name; }
			set	
			{
				if( value!= null && value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for TsiName", value, value.ToString());
				
				_tsi_name = value;
			}
		}
			
		/// <summary>
		/// 第三方名称
		/// </summary>		
		public string TsiDealerName
		{
			get { return _tsi_dealername; }
			set	
			{
				if( value!= null && value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for TsiDealerName", value, value.ToString());
				
				_tsi_dealername = value;
			}
		}
			
		/// <summary>
		/// 日期
		/// </summary>		
		public DateTime? TsiTrainingDate
		{
			get { return _tsi_trainingdate; }
			set { _tsi_trainingdate = value; }
		}
			
		/// <summary>
		/// 创建日期
		/// </summary>		
		public DateTime? BlCreateDate
		{
			get { return _bl_create_date; }
			set { _bl_create_date = value; }
		}
			
		/// <summary>
		/// 创建人
		/// </summary>		
		public Guid? BlCreateUser
		{
			get { return _bl_create_user; }
			set { _bl_create_user = value; }
		}
			
		/// <summary>
		/// 更新日期
		/// </summary>		
		public DateTime? BlUpdateDate
		{
			get { return _bl_update_date; }
			set { _bl_update_date = value; }
		}
			
		/// <summary>
		/// 更新人
		/// </summary>		
		public Guid? BlUpdateUser
		{
			get { return _bl_update_user; }
			set { _bl_update_user = value; }
		}
			
		
	
		
		#endregion 
		
		
		
		
		
	}
}
