/*
 * Ibatis.Net for Data Mapper, and Generated by MyGeneration
 * 
 * NameSpace   : DMS.Model 
 * ClassName   : ShipmentlpConfirmDetail
 * Created Time: 2014/5/30 13:06:36
 *
 ******* Copyright (C) 2009/2010 - GrapeCity **********
 *
******************************************************/

using System;

namespace DMS.Model
{
	/// <summary>
	///	ShipmentlpConfirmDetail
	/// </summary>
	[Serializable]
	public class ShipmentlpConfirmDetail : BaseModel
	{
		#region Private Members 6
		
		private Guid _id; 
		private Guid _sch_id; 
		private string _upn; 
		private string _lot; 
		private decimal? _qty;
        private decimal? _unitprice;
        private bool? _iscalrebate; 	
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public ShipmentlpConfirmDetail()
		{
			_id = Guid.Empty; 
			_sch_id = Guid.Empty; 
			_upn = null; 
			_lot = null; 
			_qty = null;
            _unitprice = null;
            _iscalrebate = null;
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public Guid Id
		{
			get { return _id; }
			set { _id = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public Guid SchId
		{
			get { return _sch_id; }
			set { _sch_id = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string Upn
		{
			get { return _upn; }
			set	
			{
				if( value!= null && value.Length > 200)
					throw new ArgumentOutOfRangeException("Invalid value for Upn", value, value.ToString());
				
				_upn = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string Lot
		{
			get { return _lot; }
			set	
			{
				if( value!= null && value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Lot", value, value.ToString());
				
				_lot = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public decimal? Qty
		{
			get { return _qty; }
			set { _qty = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public decimal? UnitPrice
		{
			get { return _unitprice; }
			set { _unitprice = value; }
		}

        /// <summary>
        /// 
        /// </summary>		
        public bool? IsCalRebate
        {
            get { return _iscalrebate; }
            set { _iscalrebate = value; }
        }
	
		
		#endregion 
		
		
		
		
		
	}
}
