ALTER TABLE interface.RV_DealerKPI_Score_Warning ADD Dealerlevel NVARCHAR(100);
GO

--经销商分级
DELETE Lafite_DICT WHERE DICT_TYPE = 'CONST_DP_DealerLevel';
DELETE Lafite_DICTTYPE WHERE DICT_TYPE = 'CONST_DP_DealerLevel';
INSERT INTO Lafite_DICTTYPE (DICT_TYPE,DICT_TYPE_NAME,DESCRIPTION,SORT_COL,APP_ID,SYS_FLAG) 
VALUES ('CONST_DP_DealerLevel','经销商分级','',0,'4028931b0f0fc135010f0fc1356a0001',0);
INSERT INTO dbo.Lafite_DICT (Id,DICT_LEVEL,DICT_TYPE,DICT_KEY,VALUE1,ACTIVE_FLAG,APP_ID,SORT_COL,DELETE_FLAG,CREATE_USER,CREATE_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
VALUES (newid(),1,'CONST_DP_DealerLevel','VIP+','VIP+',1,'4028931b0f0fc135010f0fc1356a0001',1,0,'mmbo',getdate(),'mmbo',getdate());
INSERT INTO dbo.Lafite_DICT (Id,DICT_LEVEL,DICT_TYPE,DICT_KEY,VALUE1,ACTIVE_FLAG,APP_ID,SORT_COL,DELETE_FLAG,CREATE_USER,CREATE_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
VALUES (newid(),1,'CONST_DP_DealerLevel','VIP','VIP',1,'4028931b0f0fc135010f0fc1356a0001',2,0,'mmbo',getdate(),'mmbo',getdate());
INSERT INTO dbo.Lafite_DICT (Id,DICT_LEVEL,DICT_TYPE,DICT_KEY,VALUE1,ACTIVE_FLAG,APP_ID,SORT_COL,DELETE_FLAG,CREATE_USER,CREATE_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
VALUES (newid(),1,'CONST_DP_DealerLevel','B+','B+',1,'4028931b0f0fc135010f0fc1356a0001',3,0,'mmbo',getdate(),'mmbo',getdate());
INSERT INTO dbo.Lafite_DICT (Id,DICT_LEVEL,DICT_TYPE,DICT_KEY,VALUE1,ACTIVE_FLAG,APP_ID,SORT_COL,DELETE_FLAG,CREATE_USER,CREATE_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
VALUES (newid(),1,'CONST_DP_DealerLevel','B','B',1,'4028931b0f0fc135010f0fc1356a0001',4,0,'mmbo',getdate(),'mmbo',getdate());
INSERT INTO dbo.Lafite_DICT (Id,DICT_LEVEL,DICT_TYPE,DICT_KEY,VALUE1,ACTIVE_FLAG,APP_ID,SORT_COL,DELETE_FLAG,CREATE_USER,CREATE_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
VALUES (newid(),1,'CONST_DP_DealerLevel','C','C',1,'4028931b0f0fc135010f0fc1356a0001',5,0,'mmbo',getdate(),'mmbo',getdate());
INSERT INTO dbo.Lafite_DICT (Id,DICT_LEVEL,DICT_TYPE,DICT_KEY,VALUE1,ACTIVE_FLAG,APP_ID,SORT_COL,DELETE_FLAG,CREATE_USER,CREATE_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
VALUES (newid(),1,'CONST_DP_DealerLevel','D','D',1,'4028931b0f0fc135010f0fc1356a0001',6,0,'mmbo',getdate(),'mmbo',getdate());

--重点医院
DELETE Lafite_DICT WHERE DICT_TYPE = 'CONST_DP_KeyHospital';
DELETE Lafite_DICTTYPE WHERE DICT_TYPE = 'CONST_DP_KeyHospital';
INSERT INTO Lafite_DICTTYPE (DICT_TYPE,DICT_TYPE_NAME,DESCRIPTION,SORT_COL,APP_ID,SYS_FLAG) 
VALUES ('CONST_DP_KeyHospital','重点医院','',0,'4028931b0f0fc135010f0fc1356a0001',0);
INSERT INTO dbo.Lafite_DICT (Id,DICT_LEVEL,DICT_TYPE,DICT_KEY,VALUE1,ACTIVE_FLAG,APP_ID,SORT_COL,DELETE_FLAG,CREATE_USER,CREATE_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
VALUES (newid(),1,'CONST_DP_KeyHospital','1','是',1,'4028931b0f0fc135010f0fc1356a0001',1,0,'mmbo',getdate(),'mmbo',getdate());
INSERT INTO dbo.Lafite_DICT (Id,DICT_LEVEL,DICT_TYPE,DICT_KEY,VALUE1,ACTIVE_FLAG,APP_ID,SORT_COL,DELETE_FLAG,CREATE_USER,CREATE_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
VALUES (newid(),1,'CONST_DP_KeyHospital','0','否',1,'4028931b0f0fc135010f0fc1356a0001',2,0,'mmbo',getdate(),'mmbo',getdate());

--DP.Proc_GetBscFeedbackDealerList
--DP.Proc_GetBscFeedbackHospitalList
--DP.Proc_GetBscFeedbackAllDealerList
--DP.Proc_GetBscFeedbackAllHospitalList
--DP.Proc_ExportBscFeedback