/*
 * Ibatis.Net for Data Mapper, and Generated by MyGeneration
 * 
 * NameSpace   : DMS.Model 
 * ClassName   : MailMessageTemplate
 * Created Time: 2011-3-24 11:56:29
 *
 ******* Copyright (C) 2009/2010 - GrapeCity **********
 *
******************************************************/

using System;

namespace DMS.Model
{
	/// <summary>
	///	MailMessageTemplate
	/// </summary>
	[Serializable]
	public class MailMessageTemplate : BaseModel
	{
		#region Private Members 4
		
		private Guid _id; 
		private string _code; 
		private string _subject; 
		private string _body; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public MailMessageTemplate()
		{
			_id = Guid.Empty; 
			_code = null; 
			_subject = null; 
			_body = null; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 主键
		/// </summary>		
		public Guid Id
		{
			get { return _id; }
			set { _id = value; }
		}
			
		/// <summary>
		/// 代码
		/// </summary>		
		public string Code
		{
			get { return _code; }
			set	
			{
				if( value!= null && value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Code", value, value.ToString());
				
				_code = value;
			}
		}
			
		/// <summary>
		/// 主体模板
		/// </summary>		
		public string Subject
		{
			get { return _subject; }
			set	
			{
				if( value!= null && value.Length > 200)
					throw new ArgumentOutOfRangeException("Invalid value for Subject", value, value.ToString());
				
				_subject = value;
			}
		}
			
		/// <summary>
		/// 内容模板
		/// </summary>		
		public string Body
		{
			get { return _body; }
			set	
			{
				if( value!= null && value.Length > 1000)
					throw new ArgumentOutOfRangeException("Invalid value for Body", value, value.ToString());
				
				_body = value;
			}
		}
			
		
	
		
		#endregion 
		
		
		
		
		
	}
}
