/*
 * Ibatis.Net for Data Mapper, and Generated by MyGeneration
 * 
 * NameSpace   : DMS.Model 
 * ClassName   : DealerOrderNumber
 * Created Time: 2011-3-2 10:34:26
 *
 ******* Copyright (C) 2009/2010 - GrapeCity **********
 *
******************************************************/

using System;

namespace DMS.Model
{
	/// <summary>
	///	DealerOrderNumber
	/// </summary>
	[Serializable]
	public class DealerOrderNumber : BaseModel
	{
		#region Private Members 6
		
		private Guid _id; 
		private Guid _dma_id; 
		private Guid _cfn_id; 
		private Guid _bum_id; 
		private decimal _price; 
		private decimal _qty; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public DealerOrderNumber()
		{
			_id = Guid.Empty; 
			_dma_id = Guid.Empty; 
			_cfn_id = Guid.Empty; 
			_bum_id = Guid.Empty; 
			_price = 0; 
			_qty = 0; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 主键
		/// </summary>		
		public Guid Id
		{
			get { return _id; }
			set { _id = value; }
		}
			
		/// <summary>
		/// 经销商主键
		/// </summary>		
		public Guid DmaId
		{
			get { return _dma_id; }
			set { _dma_id = value; }
		}
			
		/// <summary>
		/// 产品主键
		/// </summary>		
		public Guid CfnId
		{
			get { return _cfn_id; }
			set { _cfn_id = value; }
		}
			
		/// <summary>
		/// 产品线主键
		/// </summary>		
		public Guid BumId
		{
			get { return _bum_id; }
			set { _bum_id = value; }
		}
			
		/// <summary>
		/// 产品价格
		/// </summary>		
		public decimal Price
		{
			get { return _price; }
			set { _price = value; }
		}
			
		/// <summary>
		/// 订购数量
		/// </summary>		
		public decimal Qty
		{
			get { return _qty; }
			set { _qty = value; }
		}
			
		
	
		
		#endregion 
		
		
		
		
		
	}
}
