DROP PROCEDURE [Promotion].[Proc_Pro_Cal] 
GO

CREATE PROCEDURE [Promotion].[Proc_Pro_Cal] 
AS
BEGIN
	

	DECLARE @PolicyId INT 
	
	--循环当前可计算政策
	DECLARE @iCURSOR CURSOR;
	SET @iCURSOR = CURSOR FOR SELECT A.PolicyId FROM Promotion.PRO_POLICY a 
		WHERE Status = '有效' AND CalModule = '正式' AND CalStatus = '待计算' 
		AND PolicyStyle <> '即时买赠'
	OPEN @iCURSOR 	
	FETCH NEXT FROM @iCURSOR INTO @PolicyId
	WHILE @@FETCH_STATUS = 0
	BEGIN
		PRINT 'Policyid = '+CONVERT(NVARCHAR,@PolicyId) +' Caculate Start!' 
		
		UPDATE Promotion.PRO_POLICY SET StartTime = GETDATE() WHERE PolicyId = @PolicyId
		
		EXEC PROMOTION.Proc_Pro_Cal_Policy @PolicyId	--逐条计算政策
		
		FETCH NEXT FROM @iCURSOR INTO @PolicyId
	END	
	CLOSE @iCURSOR
	DEALLOCATE @iCURSOR
	
	--进入预算接口表
	DECLARE @CREATETIME DATETIME;
	
	SET @CREATETIME = GETDATE();
	
	INSERT INTO Promotion.Pro_Forecast_Log(YEARMONTH,CHECKPT,STARTDATE,ENDDATE,STATUS,CREATEDATE) 
		SELECT CONVERT(NVARCHAR(7),GETDATE(),121),'Actual',
			CONVERT(NVARCHAR(10),DATEADD(Q,-1,CONVERT(DATETIME,CONVERT(NVARCHAR(4),GETDATE(),121)+CASE DATEPART(Q,GETDATE()) WHEN 1 THEN '01' WHEN 2 THEN '04' WHEN 3 THEN '07' ELSE '10' END+'01')),121),	--季度首日
			CONVERT(NVARCHAR(10),DATEADD(D,-1,CONVERT(DATETIME,CONVERT(NVARCHAR(4),GETDATE(),121)+CASE DATEPART(Q,GETDATE()) WHEN 1 THEN '01' WHEN 2 THEN '04' WHEN 3 THEN '07' ELSE '10' END+'01')),121), --季度末日
			'Running',@CREATETIME
	
	DECLARE @iCURSOR_Forecast CURSOR;
	SET @iCURSOR_Forecast = CURSOR FOR SELECT A.PolicyId FROM Promotion.PRO_POLICY a 
		WHERE Status = '有效' AND CalModule = '正式' AND CalStatus = '计算完成'
		AND PolicyStyle <> '即时买赠'
	OPEN @iCURSOR_Forecast 	
	FETCH NEXT FROM @iCURSOR_Forecast INTO @PolicyId
	WHILE @@FETCH_STATUS = 0
	BEGIN
		EXEC PROMOTION.Proc_Pro_Cal_Forecast_Closing @PolicyId,@CREATETIME
		
		FETCH NEXT FROM @iCURSOR_Forecast INTO @PolicyId
	END	
	CLOSE @iCURSOR_Forecast
	DEALLOCATE @iCURSOR_Forecast
	
	UPDATE A SET STATUS = 'Success',UPDATEDATE=GETDATE()
	FROM Promotion.Pro_Forecast_Log A WHERE YEARMONTH = CONVERT(NVARCHAR(7),GETDATE(),121) 
	AND CHECKPT = 'Actual' AND STATUS ='Running' AND CREATEDATE = @CREATETIME
	
END

GO


