/*
 * Ibatis.Net for Data Mapper, and Generated by MyGeneration
 * 
 * NameSpace   : DMS.Model 
 * ClassName   : InterfaceDealerSalesWriteback
 * Created Time: 2014/3/19 12:09:32
 *
 ******* Copyright (C) 2009/2010 - GrapeCity **********
 *
******************************************************/

using System;

namespace DMS.Model
{
	/// <summary>
	///	InterfaceDealerSalesWriteback
	/// </summary>
	[Serializable]
	public class InterfaceDealerSalesWriteback : BaseModel
	{
		#region Private Members 9
		
		private Guid _id; 
		private string _writebackno; 
		private string _salesno; 
		private DateTime? _writebackdate; 
		private string _remark; 
		private int _linenbr;
        private Guid _shipmentid;
		private DateTime _importdate; 
		private string _clientid; 
		private string _batchnbr;
        private string _errormsg;
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public InterfaceDealerSalesWriteback()
		{
			_id = Guid.Empty; 
			_writebackno = null; 
			_salesno = null; 
			_writebackdate = null;
			_remark = null; 
			_linenbr = 0;
            _shipmentid = Guid.Empty;
			_importdate = new DateTime(); 
			_clientid = null; 
			_batchnbr = null;
            _errormsg = null;
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 主键
		/// </summary>		
		public Guid Id
		{
			get { return _id; }
			set { _id = value; }
		}
			
		/// <summary>
		/// 冲红单编号
		/// </summary>		
		public string WriteBackNo
		{
			get { return _writebackno; }
			set	
			{
				if( value!= null && value.Length > 30)
					throw new ArgumentOutOfRangeException("Invalid value for WriteBackNo", value, value.ToString());
				
				_writebackno = value;
			}
		}
			
		/// <summary>
		/// 需冲红销售单编号
		/// </summary>		
		public string SalesNo
		{
			get { return _salesno; }
			set	
			{
				if( value!= null && value.Length > 30)
					throw new ArgumentOutOfRangeException("Invalid value for SalesNo", value, value.ToString());
				
				_salesno = value;
			}
		}
			
		/// <summary>
		/// 冲红日期
		/// </summary>		
		public DateTime? WriteBackDate
		{
			get { return _writebackdate; }
			set { _writebackdate = value; }
		}
			
		/// <summary>
		/// 备注
		/// </summary>		
		public string Remark
		{
			get { return _remark; }
			set	
			{
				if( value!= null && value.Length > 200)
					throw new ArgumentOutOfRangeException("Invalid value for Remark", value, value.ToString());
				
				_remark = value;
			}
		}
			
		/// <summary>
		/// 行号
		/// </summary>		
		public int LineNbr
		{
			get { return _linenbr; }
			set { _linenbr = value; }
		}
        /// <summary>
        /// 销售单ID
        /// </summary>		
        public Guid ShipmentId
        {
            get { return _shipmentid; }
            set { _shipmentid = value; }
        }

		/// <summary>
		/// 导入时间
		/// </summary>		
		public DateTime ImportDate
		{
			get { return _importdate; }
			set { _importdate = value; }
		}
			
		/// <summary>
		/// 客户端ID
		/// </summary>		
		public string Clientid
		{
			get { return _clientid; }
			set	
			{
				if( value!= null && value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Clientid", value, value.ToString());
				
				_clientid = value;
			}
		}
			
		/// <summary>
		/// 处理批次
		/// </summary>		
		public string BatchNbr
		{
			get { return _batchnbr; }
			set	
			{
				if( value!= null && value.Length > 30)
					throw new ArgumentOutOfRangeException("Invalid value for BatchNbr", value, value.ToString());
				
				_batchnbr = value;
			}
		}

        /// <summary>
        /// 处理错误信息
        /// </summary>		
        public string ErrorMsg
        {
            get { return _errormsg; }
            set
            {
                if (value != null && value.Length > 2000)
                    throw new ArgumentOutOfRangeException("Invalid value for ErrorMsg", value, value.ToString());

                _errormsg = value;
            }
        }
	
		
		#endregion 
		
		
		
		
		
	}
}
