DROP VIEW [Promotion].[V_PRO_FORECAST_POLICY_UPN]
GO


CREATE VIEW [Promotion].[V_PRO_FORECAST_POLICY_UPN]
AS 
SELECT B.PolicyId,B.UPN,A.CreateTime
FROM Promotion.PRO_FORECAST_POLICY A,Promotion.PRO_FORECAST_POLICY_UPN B 
WHERE largessAmount <>0 AND A.POLICYID = B.POLICYID


GO


