DROP VIEW [Promotion].[V_PRO_FORECAST_POLICY_DETAIL]
GO


CREATE VIEW [Promotion].[V_PRO_FORECAST_POLICY_DETAIL]
AS 
SELECT B.PolicyId,OperTag,ConditionValue
FROM Promotion.PRO_FORECAST_POLICY A,Promotion.PRO_FORECAST_POLICY_DETAIL B 
WHERE A.POLICYID = B.POLICYID AND largessAmount <>0
GO


