DROP VIEW [Promotion].[V_PRO_FORECAST_DEALER_UPN]
GO


CREATE VIEW [Promotion].[V_PRO_FORECAST_DEALER_UPN]
AS 
SELECT B.DLid,B.UPN, A.CreateTime
FROM Promotion.PRO_FORECAST_DEALER A,Promotion.PRO_FORECAST_DEALER_UPN B 
WHERE largessAmount <>0 AND A.DLID = B.DLID



GO


