/*
 * Ibatis.Net for Data Mapper, and Generated by MyGeneration
 * 
 * NameSpace   : DMS.Model 
 * ClassName   : ArrivalDateInit
 * Created Time: 2011-2-10 11:59:48
 *
 ******* Copyright (C) 2009/2010 - GrapeCity **********
 *
******************************************************/

using System;

namespace DMS.Model
{
	/// <summary>
	///	ArrivalDateInit
	/// </summary>
	[Serializable]
	public class ArrivalDateInit : BaseModel
	{
		#region Private Members 10
		
		private Guid _id; 
		private Guid _user; 
		private DateTime _uploaddate; 
		private int _linenbr; 
		private string _filename; 
		private bool _errorflag; 
		private string _errordescription; 
		private string _carrier; 
		private string _trackingno; 
		private DateTime? _arrivaldate; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public ArrivalDateInit()
		{
			_id = Guid.Empty; 
			_user = Guid.Empty; 
			_uploaddate = new DateTime(); 
			_linenbr = 0; 
			_filename = null; 
			_errorflag = false; 
			_errordescription = null; 
			_carrier = null; 
			_trackingno = null; 
			_arrivaldate = null;
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 主键
		/// </summary>		
		public Guid Id
		{
			get { return _id; }
			set { _id = value; }
		}
			
		/// <summary>
		/// 上传用户
		/// </summary>		
		public Guid User
		{
			get { return _user; }
			set { _user = value; }
		}
			
		/// <summary>
		/// 上传时间
		/// </summary>		
		public DateTime UploadDate
		{
			get { return _uploaddate; }
			set { _uploaddate = value; }
		}
			
		/// <summary>
		/// 行号
		/// </summary>		
		public int LineNbr
		{
			get { return _linenbr; }
			set { _linenbr = value; }
		}
			
		/// <summary>
		/// 文件名
		/// </summary>		
		public string FileName
		{
			get { return _filename; }
			set	
			{
				if( value!= null && value.Length > 200)
					throw new ArgumentOutOfRangeException("Invalid value for FileName", value, value.ToString());
				
				_filename = value;
			}
		}
			
		/// <summary>
		/// 错误标识
		/// </summary>		
		public bool ErrorFlag
		{
			get { return _errorflag; }
			set { _errorflag = value; }
		}
			
		/// <summary>
		/// 错误信息
		/// </summary>		
		public string ErrorDescription
		{
			get { return _errordescription; }
			set	
			{
				if( value!= null && value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for ErrorDescription", value, value.ToString());
				
				_errordescription = value;
			}
		}
			
		/// <summary>
		/// 承运方
		/// </summary>		
		public string Carrier
		{
			get { return _carrier; }
			set	
			{
				if( value!= null && value.Length > 20)
					throw new ArgumentOutOfRangeException("Invalid value for Carrier", value, value.ToString());
				
				_carrier = value;
			}
		}
			
		/// <summary>
		/// 运单号
		/// </summary>		
		public string TrackingNo
		{
			get { return _trackingno; }
			set	
			{
				if( value!= null && value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for TrackingNo", value, value.ToString());
				
				_trackingno = value;
			}
		}
			
		/// <summary>
		/// 到货日期
		/// </summary>		
		public DateTime? ArrivalDate
		{
			get { return _arrivaldate; }
			set { _arrivaldate = value; }
		}
			
		
	
		
		#endregion 
		
		
		
		
		
	}
}
