/*
 * Ibatis.Net for Data Mapper, and Generated by MyGeneration
 * 
 * NameSpace   : DMS.Model 
 * ClassName   : PoReceiptLot
 * Created Time: 2009-7-22 10:57:41
 *
 ******* Copyright (C) 2009/2010 - GrapeCity **********
 *
******************************************************/

using System;

namespace DMS.Model
{
	/// <summary>
	///	PoReceiptLot
	/// </summary>
	[Serializable]
	public class PoReceiptLot : BaseModel
	{
		#region Private Members
		
		private Guid _por_id; 
		private Guid _id; 
		private string _lotnumber; 
		private double _receiptqty;
        private DateTime? _expireddate;  //modify @2009/12/21 by Steven
        private Guid? _whm_id;
        private decimal? _unitprice;
        private bool? _iscalrebate; 	
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public PoReceiptLot()
		{
			_por_id = new Guid(); 
			_id = new Guid(); 
			_lotnumber = null; 
			_receiptqty = new double(); 
			_expireddate = new DateTime();
            _whm_id = null;
            _unitprice = null;
            _iscalrebate = null;
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 接收记录
		/// </summary>		
		public Guid PorId
		{
			get { return _por_id; }
			set { _por_id = value; }
		}
			
		/// <summary>
		/// 主键
		/// </summary>		
		public Guid Id
		{
			get { return _id; }
			set { _id = value; }
		}
			
		/// <summary>
		/// 批次代码
		/// </summary>		
		public string LotNumber
		{
			get { return _lotnumber; }
			set	
			{
				if( value!= null && value.Length >50)
					throw new ArgumentOutOfRangeException("Invalid value for LotNumber", value, value.ToString());
				
				_lotnumber = value;
			}
		}
			
		/// <summary>
		/// 接收批次数量
		/// </summary>		
		public double ReceiptQty
		{
			get { return _receiptqty; }
			set { _receiptqty = value; }
		}
			
		/// <summary>
		/// 过期日期
		/// </summary>		
		public DateTime? ExpiredDate  //modify @2009/12/21 by Steven
		{
			get { return _expireddate; }
			set { _expireddate = value; }
		}
			
		/// <summary>
		/// 仓库
		/// </summary>		
		public Guid? WhmId
		{
			get { return _whm_id; }
			set { _whm_id = value; }
		}

        /// <summary>
        /// 价格
        /// </summary>		
        public decimal? UnitPrice
        {
            get { return _unitprice; }
            set { _unitprice = value; }
        }

        /// <summary>
        /// 是否计算返利
        /// </summary>		
        public bool? IsCalRebate
        {
            get { return _iscalrebate; }
            set { _iscalrebate = value; }
        }
	
		
		#endregion 
		
		
		
		
		
	}
}
