/*
 * Ibatis.Net for Data Mapper, and Generated by MyGeneration
 * 
 * NameSpace   : DMS.Model 
 * ClassName   : SampleEval
 * Created Time: 2016/3/8 17:09:23
 *
 ******* Copyright (C) 2009/2010 - GrapeCity **********
 *
******************************************************/

using System;

namespace DMS.Model
{
	/// <summary>
	///	SampleEval
	/// </summary>
	[Serializable]
	public class SampleEval : BaseModel
	{
		#region Private Members 9
		
		private Guid _sampleevalid; 
		private Guid _sampleheadid; 
		private string _upnno; 
		private string _lot;
        private string _evalname;
        private string _evalurl;
        private string _createuser;
        private DateTime? _createdate;
        private string _updateuser; 
		private DateTime? _updatedate; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public SampleEval()
		{
			_sampleevalid = Guid.Empty; 
			_sampleheadid = Guid.Empty; 
			_upnno = null; 
			_lot = null; 
            _createuser = null;
            _createdate = null;
			_updateuser = null;
			_updatedate = null;
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 样品评估单ID
		/// </summary>		
		public Guid SampleEvalId
		{
			get { return _sampleevalid; }
			set { _sampleevalid = value; }
		}
			
		/// <summary>
		/// 样品主ID
		/// </summary>		
		public Guid SampleHeadId
		{
			get { return _sampleheadid; }
			set { _sampleheadid = value; }
		}
			
		/// <summary>
		/// UPN编号
		/// </summary>		
		public string UpnNo
		{
			get { return _upnno; }
			set	
			{
				if( value!= null && value.Length > 500)
					throw new ArgumentOutOfRangeException("Invalid value for UpnNo", value, value.ToString());
				
				_upnno = value;
			}
		}
			
		/// <summary>
		/// 批号
		/// </summary>		
		public string Lot
		{
			get { return _lot; }
			set	
			{
				if( value!= null && value.Length > 500)
					throw new ArgumentOutOfRangeException("Invalid value for Lot", value, value.ToString());
				
				_lot = value;
			}
		}
			
		/// <summary>
        /// 评估单文件名
		/// </summary>		
		public string EvalName
		{
            get { return _evalname; }
            set
            {
                if (value != null && value.Length > 500)
                    throw new ArgumentOutOfRangeException("Invalid value for EvalName", value, value.ToString());

                _evalname = value;
            }
		}

        /// <summary>
        /// 评估单地址
        /// </summary>		
        public string EvalUrl
        {
            get { return _evalurl; }
            set
            {
                if (value != null && value.Length > 500)
                    throw new ArgumentOutOfRangeException("Invalid value for EvalUrl", value, value.ToString());

                _evalurl = value;
            }
        }

        /// <summary>
        /// 创建人
        /// </summary>		
        public string CreateUser
        {
            get { return _createuser; }
            set
            {
                if (value != null && value.Length > 20)
                    throw new ArgumentOutOfRangeException("Invalid value for CreateUser", value, value.ToString());

                _createuser = value;
            }
        }

        /// <summary>
        /// 创建时间
        /// </summary>		
        public DateTime? CreateDate
        {
            get { return _createdate; }
            set { _createdate = value; }
        }

        /// <summary>
        /// 更新人
        /// </summary>		
        public string UpdateUser
        {
            get { return _updateuser; }
            set
            {
                if (value != null && value.Length > 20)
                    throw new ArgumentOutOfRangeException("Invalid value for UpdateUser", value, value.ToString());

                _updateuser = value;
            }
        }
			
		/// <summary>
		/// 更新时间
		/// </summary>		
		public DateTime? UpdateDate
		{
			get { return _updatedate; }
			set { _updatedate = value; }
		}
			
		
	
		
		#endregion 
		
		
		
		
		
	}
}
