//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Website.Pages.Promotion {
    
    
    public partial class PromotionMaintain {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.ScriptManager ScriptManager1;
        
        /// <summary>
        /// FactorConditionStore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Store FactorConditionStore;
        
        /// <summary>
        /// FactorConditionTypeStore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Store FactorConditionTypeStore;
        
        /// <summary>
        /// Wd3RuleStore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Store Wd3RuleStore;
        
        /// <summary>
        /// Wd3RuleSeletedStore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Store Wd3RuleSeletedStore;
        
        /// <summary>
        /// Wd3FactorRelationStore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Store Wd3FactorRelationStore;
        
        /// <summary>
        /// FolicyFactorStore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Store FolicyFactorStore;
        
        /// <summary>
        /// PolicyFactorRuleStore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Store PolicyFactorRuleStore;
        
        /// <summary>
        /// PolicyDealerCanStore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Store PolicyDealerCanStore;
        
        /// <summary>
        /// PolicyDealerSeletedStore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Store PolicyDealerSeletedStore;
        
        /// <summary>
        /// FactorRuleStore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Store FactorRuleStore;
        
        /// <summary>
        /// PolicyFactorXStore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Store PolicyFactorXStore;
        
        /// <summary>
        /// AttachmentStore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Store AttachmentStore;
        
        /// <summary>
        /// hidurl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Hidden hidurl;
        
        /// <summary>
        /// Hidattmentid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Hidden Hidattmentid;
        
        /// <summary>
        /// HidFactorId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Hidden HidFactorId;
        
        /// <summary>
        /// HidFactConditionId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Hidden HidFactConditionId;
        
        /// <summary>
        /// HidPolicyStyle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Hidden HidPolicyStyle;
        
        /// <summary>
        /// PolicyFactorId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Hidden PolicyFactorId;
        
        /// <summary>
        /// hiddenMainId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Hidden hiddenMainId;
        
        /// <summary>
        /// hiddenCountAttachment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Hidden hiddenCountAttachment;
        
        /// <summary>
        /// BatchNbr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Hidden BatchNbr;
        
        /// <summary>
        /// hidFactId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Hidden hidFactId;
        
        /// <summary>
        /// hidWd4PolicyRuleId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Hidden hidWd4PolicyRuleId;
        
        /// <summary>
        /// hidWd4PolicyFactorX control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Hidden hidWd4PolicyFactorX;
        
        /// <summary>
        /// hidid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Hidden hidid;
        
        /// <summary>
        /// Productline control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Hidden Productline;
        
        /// <summary>
        /// pagetype control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Hidden pagetype;
        
        /// <summary>
        /// state control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Hidden state;
        
        /// <summary>
        /// ViewPort1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.ViewPort ViewPort1;
        
        /// <summary>
        /// BorderLayout1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.BorderLayout BorderLayout1;
        
        /// <summary>
        /// Panel2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel Panel2;
        
        /// <summary>
        /// DivSampleBusiness control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FieldSet DivSampleBusiness;
        
        /// <summary>
        /// a control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FormLayout a;
        
        /// <summary>
        /// Panel3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel Panel3;
        
        /// <summary>
        /// ColumnLayout1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.ColumnLayout ColumnLayout1;
        
        /// <summary>
        /// Panel4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel Panel4;
        
        /// <summary>
        /// FormLayout1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FormLayout FormLayout1;
        
        /// <summary>
        /// PromotionID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.TextField PromotionID;
        
        /// <summary>
        /// Panel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel Panel1;
        
        /// <summary>
        /// FormLayout2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FormLayout FormLayout2;
        
        /// <summary>
        /// type control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.ComboBox type;
        
        /// <summary>
        /// Panel5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel Panel5;
        
        /// <summary>
        /// FormLayout3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FormLayout FormLayout3;
        
        /// <summary>
        /// PolicyTypeNow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.TextField PolicyTypeNow;
        
        /// <summary>
        /// Panel9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel Panel9;
        
        /// <summary>
        /// FormLayout6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FormLayout FormLayout6;
        
        /// <summary>
        /// PolicyTypeChange control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.ComboBox PolicyTypeChange;
        
        /// <summary>
        /// Btnadjustment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Button Btnadjustment;
        
        /// <summary>
        /// FieldSet1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FieldSet FieldSet1;
        
        /// <summary>
        /// FormLayout7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FormLayout FormLayout7;
        
        /// <summary>
        /// Panel11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel Panel11;
        
        /// <summary>
        /// ColumnLayout3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.ColumnLayout ColumnLayout3;
        
        /// <summary>
        /// Panel12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel Panel12;
        
        /// <summary>
        /// FormLayout8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FormLayout FormLayout8;
        
        /// <summary>
        /// txtReceiptNo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.TextField txtReceiptNo;
        
        /// <summary>
        /// Label1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Label Label1;
        
        /// <summary>
        /// BtnOrderQuery control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Button BtnOrderQuery;
        
        /// <summary>
        /// BtnOrderUpdate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Button BtnOrderUpdate;
        
        /// <summary>
        /// FieldSet2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FieldSet FieldSet2;
        
        /// <summary>
        /// FormLayout9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FormLayout FormLayout9;
        
        /// <summary>
        /// Panel13 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel Panel13;
        
        /// <summary>
        /// ColumnLayout4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.ColumnLayout ColumnLayout4;
        
        /// <summary>
        /// Panel14 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel Panel14;
        
        /// <summary>
        /// FormLayout10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FormLayout FormLayout10;
        
        /// <summary>
        /// txtReceiptNo2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.TextField txtReceiptNo2;
        
        /// <summary>
        /// message control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Label message;
        
        /// <summary>
        /// BtnProQuery2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Button BtnProQuery2;
        
        /// <summary>
        /// BtnOrderUpdate2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Button BtnOrderUpdate2;
        
        /// <summary>
        /// FieldSet3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FieldSet FieldSet3;
        
        /// <summary>
        /// Panel15 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel Panel15;
        
        /// <summary>
        /// GpWdAttachment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.GridPanel GpWdAttachment;
        
        /// <summary>
        /// RowSelectionModel5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.RowSelectionModel RowSelectionModel5;
        
        /// <summary>
        /// PagingToolBarAttachment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.PagingToolbar PagingToolBarAttachment;
        
        /// <summary>
        /// wdAttachment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Window wdAttachment;
        
        /// <summary>
        /// AttachmentForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FormPanel AttachmentForm;
        
        /// <summary>
        /// FormLayout24 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FormLayout FormLayout24;
        
        /// <summary>
        /// ufUploadAttachment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FileUploadField ufUploadAttachment;
        
        /// <summary>
        /// btnWinAttachmentSubmit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Button btnWinAttachmentSubmit;
        
        /// <summary>
        /// Button2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Button Button2;
        
        /// <summary>
        /// wd7PolicyDealer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Window wd7PolicyDealer;
        
        /// <summary>
        /// FormLayout20 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FormLayout FormLayout20;
        
        /// <summary>
        /// PanelWd3PolicyFactor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel PanelWd3PolicyFactor;
        
        /// <summary>
        /// FormLayout21 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FormLayout FormLayout21;
        
        /// <summary>
        /// txtWd7DealerName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.TextField txtWd7DealerName;
        
        /// <summary>
        /// btnWd7PolicyDealerQuery control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Button btnWd7PolicyDealerQuery;
        
        /// <summary>
        /// PanelWd3AddFactorCondition control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel PanelWd3AddFactorCondition;
        
        /// <summary>
        /// FitLayout3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FitLayout FitLayout3;
        
        /// <summary>
        /// GridWd7PolicyDealer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.GridPanel GridWd7PolicyDealer;
        
        /// <summary>
        /// RowSelectionModel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.RowSelectionModel RowSelectionModel1;
        
        /// <summary>
        /// PagingToolBarPolicyDealersCan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.PagingToolbar PagingToolBarPolicyDealersCan;
        
        /// <summary>
        /// PanelWd3PolicyDealerSelected control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel PanelWd3PolicyDealerSelected;
        
        /// <summary>
        /// FitLayout1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FitLayout FitLayout1;
        
        /// <summary>
        /// GridWd3PolicyDealerSeleted control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.GridPanel GridWd3PolicyDealerSeleted;
        
        /// <summary>
        /// RowSelectionModel2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.RowSelectionModel RowSelectionModel2;
        
        /// <summary>
        /// PagingToolBarPolicyDealersSelected control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.PagingToolbar PagingToolBarPolicyDealersSelected;
        
        /// <summary>
        /// btnPolicyDealerCancel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Button btnPolicyDealerCancel;
        
        /// <summary>
        /// wd4PolicyRule control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Window wd4PolicyRule;
        
        /// <summary>
        /// BorderLayout2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.BorderLayout BorderLayout2;
        
        /// <summary>
        /// GridFactorRule control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.GridPanel GridFactorRule;
        
        /// <summary>
        /// RowSelectionModel3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.RowSelectionModel RowSelectionModel3;
        
        /// <summary>
        /// PagingToolBarFactorRule control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.PagingToolbar PagingToolBarFactorRule;
        
        /// <summary>
        /// Button4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Button Button4;
        
        /// <summary>
        /// WindowPromotionType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Window WindowPromotionType;
        
        /// <summary>
        /// BorderLayout4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.BorderLayout BorderLayout4;
        
        /// <summary>
        /// Panel10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel Panel10;
        
        /// <summary>
        /// Panel8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel Panel8;
        
        /// <summary>
        /// ColumnLayout2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.ColumnLayout ColumnLayout2;
        
        /// <summary>
        /// Panel6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel Panel6;
        
        /// <summary>
        /// FormLayout4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FormLayout FormLayout4;
        
        /// <summary>
        /// cbWd4PolicyFactorX control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.ComboBox cbWd4PolicyFactorX;
        
        /// <summary>
        /// txtWd4FactorRemarkX control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.TextField txtWd4FactorRemarkX;
        
        /// <summary>
        /// cbWd4PolicyFactorY control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.ComboBox cbWd4PolicyFactorY;
        
        /// <summary>
        /// txtWd4FactorRemarkY control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.TextField txtWd4FactorRemarkY;
        
        /// <summary>
        /// txtFactorValueX control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.NumberField txtFactorValueX;
        
        /// <summary>
        /// txtFactorValueY control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.NumberField txtFactorValueY;
        
        /// <summary>
        /// Panel7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel Panel7;
        
        /// <summary>
        /// FormLayout5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FormLayout FormLayout5;
        
        /// <summary>
        /// areaWd4Desc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.TextArea areaWd4Desc;
        
        /// <summary>
        /// btnWd4AddFactor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Button btnWd4AddFactor;
        
        /// <summary>
        /// CloseButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Button CloseButton;
        
        /// <summary>
        /// PolicyFactorswindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Window PolicyFactorswindow;
        
        /// <summary>
        /// BorderLayout3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.BorderLayout BorderLayout3;
        
        /// <summary>
        /// GridFolicyFactor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.GridPanel GridFolicyFactor;
        
        /// <summary>
        /// RowSelectionModel4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.RowSelectionModel RowSelectionModel4;
        
        /// <summary>
        /// PagingToolBarFactor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.PagingToolbar PagingToolBarFactor;
        
        /// <summary>
        /// Button1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Button Button1;
        
        /// <summary>
        /// wd2PolicyFactor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Window wd2PolicyFactor;
        
        /// <summary>
        /// FormLayout11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FormLayout FormLayout11;
        
        /// <summary>
        /// PanelWd2PolicyFactor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel PanelWd2PolicyFactor;
        
        /// <summary>
        /// FormLayout12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FormLayout FormLayout12;
        
        /// <summary>
        /// cbWd2Factor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.ComboBox cbWd2Factor;
        
        /// <summary>
        /// txaWd2Remark control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.TextArea txaWd2Remark;
        
        /// <summary>
        /// cbWd2IsGift control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.ComboBox cbWd2IsGift;
        
        /// <summary>
        /// cbWd2PointsValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.ComboBox cbWd2PointsValue;
        
        /// <summary>
        /// PanelWd2AddFactorRule control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel PanelWd2AddFactorRule;
        
        /// <summary>
        /// FitLayout2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FitLayout FitLayout2;
        
        /// <summary>
        /// GridWd2FactorRule control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.GridPanel GridWd2FactorRule;
        
        /// <summary>
        /// RowSelectionModel6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.RowSelectionModel RowSelectionModel6;
        
        /// <summary>
        /// PagingToolBar1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.PagingToolbar PagingToolBar1;
        
        /// <summary>
        /// btnWd2Submint control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Button btnWd2Submint;
        
        /// <summary>
        /// wd3PolicyFactorCondition control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Window wd3PolicyFactorCondition;
        
        /// <summary>
        /// BorderLayout5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.BorderLayout BorderLayout5;
        
        /// <summary>
        /// Panel16 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel Panel16;
        
        /// <summary>
        /// FormLayout13 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FormLayout FormLayout13;
        
        /// <summary>
        /// cbWd3FactorCondition control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.ComboBox cbWd3FactorCondition;
        
        /// <summary>
        /// cbWd3FactorConditionType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.ComboBox cbWd3FactorConditionType;
        
        /// <summary>
        /// txtWd3KeyValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.TextField txtWd3KeyValue;
        
        /// <summary>
        /// Panel17 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel Panel17;
        
        /// <summary>
        /// ColumnLayout5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.ColumnLayout ColumnLayout5;
        
        /// <summary>
        /// Panel19 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel Panel19;
        
        /// <summary>
        /// FormLayout15 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FormLayout FormLayout15;
        
        /// <summary>
        /// btnWd3FactorConditionQuery control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Button btnWd3FactorConditionQuery;
        
        /// <summary>
        /// Panel20 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel Panel20;
        
        /// <summary>
        /// FormLayout16 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FormLayout FormLayout16;
        
        /// <summary>
        /// btnWd3UploadHospital control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Button btnWd3UploadHospital;
        
        /// <summary>
        /// Panel21 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel Panel21;
        
        /// <summary>
        /// FormLayout17 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FormLayout FormLayout17;
        
        /// <summary>
        /// Panel22 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel Panel22;
        
        /// <summary>
        /// FitLayout4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FitLayout FitLayout4;
        
        /// <summary>
        /// GridWd3FactorRuleCondition control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.GridPanel GridWd3FactorRuleCondition;
        
        /// <summary>
        /// RowSelectionModel7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.RowSelectionModel RowSelectionModel7;
        
        /// <summary>
        /// PagingToolBar2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.PagingToolbar PagingToolBar2;
        
        /// <summary>
        /// Panel23 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel Panel23;
        
        /// <summary>
        /// FormLayout19 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FormLayout FormLayout19;
        
        /// <summary>
        /// PanelWd3AddFactorConditionSelected control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Panel PanelWd3AddFactorConditionSelected;
        
        /// <summary>
        /// FitLayout5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FitLayout FitLayout5;
        
        /// <summary>
        /// GridWd3FactorRuleConditionSeleted control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.GridPanel GridWd3FactorRuleConditionSeleted;
        
        /// <summary>
        /// RowSelectionModel8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.RowSelectionModel RowSelectionModel8;
        
        /// <summary>
        /// PagingToolBar3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.PagingToolbar PagingToolBar3;
        
        /// <summary>
        /// Button3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Button Button3;
    }
}
