DROP VIEW [dbo].[View_BU]
GO

CREATE VIEW [dbo].[View_BU]
AS
SELECT     Id, ATTRIBUTE_TYPE, ATTRIBUTE_NAME, ATTRIBUTE_LEVEL, DESCRIPTION, REV1 as DivisionId
FROM         dbo.Lafite_ATTRIBUTE
WHERE     (DELETE_FLAG = '0') AND (ATTRIBUTE_TYPE = 'BU')

GO


