using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DMS.Common
{
    public static class WorkflowTemplate
    {
        public static string ConsignmentTemplate = "<Data><FlowId>{0}</FlowId><IgnoreAlarm>1</IgnoreAlarm><Initiator>{1}</Initiator><ApproveSelect/><Principal/><Tables><Table Name=\"BIZ_SHORTTEAM_MAIN\"><R Index=\"1\"><EID><![CDATA[{2}]]></EID><DEPID><![CDATA[{3}]]></DEPID><DMSNO><![CDATA[{4}]]></DMSNO><REQUESTTYPE><![CDATA[{5}]]></REQUESTTYPE><CONMENTMAIN><![CDATA[{6}]]></CONMENTMAIN><AMOUNT><![CDATA[{7}]]></AMOUNT><SHORTDAY><![CDATA[{8}]]></SHORTDAY></R></Table></Tables></Data>";
        public static string EndoOrderTemplate = "<Data><FlowId>{0}</FlowId><IgnoreAlarm>1</IgnoreAlarm><Initiator>{1}</Initiator><ApproveSelect/><Principal/><Tables><Table Name=\"BIZ_ENDO_ORDER_MAIN\"><R Index=\"1\"><EID><![CDATA[{2}]]></EID><REQUESTTYPE>1</REQUESTTYPE><DEPID><![CDATA[{3}]]></DEPID><DMSNO><![CDATA[{4}]]></DMSNO><CUSTXML><![CDATA[{5}]]></CUSTXML></R></Table></Tables></Data>";
        public static string EndoConsignToSaleTemplate = "<Data><FlowId>{0}</FlowId><IgnoreAlarm>1</IgnoreAlarm><Initiator>{1}</Initiator><ApproveSelect/><Principal/><Tables><Table Name=\"BIZ_ENDO_ORDER_MAIN\"><R Index=\"1\"><EID><![CDATA[{2}]]></EID><REQUESTTYPE>2</REQUESTTYPE><DEPID><![CDATA[{3}]]></DEPID><DMSNO><![CDATA[{4}]]></DMSNO><CUSTXML><![CDATA[{5}]]></CUSTXML></R></Table></Tables></Data>";
        public static string EndoGoodsReturnTemplate = "<Data><FlowId>{0}</FlowId><IgnoreAlarm>1</IgnoreAlarm><Initiator>{1}</Initiator><ApproveSelect/><Principal/><Tables><Table Name=\"BIZ_ENDO_ORDER_MAIN\"><R Index=\"1\"><EID><![CDATA[{2}]]></EID><REQUESTTYPE>3</REQUESTTYPE><DEPID><![CDATA[{3}]]></DEPID><DMSNO><![CDATA[{4}]]></DMSNO><CUSTXML><![CDATA[{5}]]></CUSTXML></R></Table></Tables></Data>";
        public static string PromotionPolicyTemplate = "<Data><FlowId>{0}</FlowId><IgnoreAlarm>1</IgnoreAlarm><Initiator>{1}</Initiator><ApproveSelect/><Principal/><Tables><Table Name=\"BIZ_PROMOTION_NEWMAIN\"><R Index=\"1\"><EID><![CDATA[{2}]]></EID><DEPID><![CDATA[{3}]]></DEPID><POLICYNO><![CDATA[{4}]]></POLICYNO><POLICY><![CDATA[{5}]]></POLICY><URL><![CDATA[{6}]]></URL><SUBBU><![CDATA[{7}]]></SUBBU></R></Table></Tables></Data>";
        public static string PromotionGiftTemplate = "<Data><FlowId>{0}</FlowId><IgnoreAlarm>1</IgnoreAlarm><Initiator>{1}</Initiator><ApproveSelect/><Principal/><Tables><Table Name=\"BIZ_PROMOTION_INTEGRAL_CALCULATE\"><R Index=\"1\"><EID><![CDATA[{2}]]></EID><REQUESTDATE><![CDATA[{3}]]></REQUESTDATE><DEPID><![CDATA[{4}]]></DEPID><CYCLE><![CDATA[{5}]]></CYCLE><TOTALAMOUNT><![CDATA[{6}]]></TOTALAMOUNT><TYPE><![CDATA[{7}]]></TYPE><DMSNO><![CDATA[{8}]]></DMSNO><CUSTXML><![CDATA[{9}]]></CUSTXML><MarketType><![CDATA[{10}]]></MarketType><SubType><![CDATA[{11}]]></SubType></R></Table></Tables></Data>";
        public static string PromotionInitPointTemplate = "<Data><FlowId>{0}</FlowId><IgnoreAlarm>1</IgnoreAlarm><Initiator>{1}</Initiator><ApproveSelect/><Principal/><Tables><Table Name=\"BIZ_PROMOTION_INTEGRAL_IMPORT\"><R Index=\"1\"><EID><![CDATA[{2}]]></EID><REQUESTDATE><![CDATA[{3}]]></REQUESTDATE><DEPID><![CDATA[{4}]]></DEPID><TYPE><![CDATA[{5}]]></TYPE><TOTALAMOUNT><![CDATA[{6}]]></TOTALAMOUNT><DMSNO><![CDATA[{7}]]></DMSNO><CUSTXML><![CDATA[{8}]]></CUSTXML><MarketType><![CDATA[{9}]]></MarketType></R></Table></Tables></Data>";
        public static string T1LpRetrunTemplate = "<Data><FlowId>{0}</FlowId><IgnoreAlarm>1</IgnoreAlarm><Initiator>{1}</Initiator><ApproveSelect/><Principal/><Tables><Table Name=\"Biz_Return_NewMain\"><R Index=\"1\"><EID><![CDATA[{2}]]></EID><DEPID><![CDATA[{3}]]></DEPID><DMSNO><![CDATA[{4}]]></DMSNO><CONMENTMAIN><![CDATA[{5}]]></CONMENTMAIN><ACTRMB><![CDATA[{6}]]></ACTRMB><RETURNTYPE><![CDATA[{7}]]></RETURNTYPE><REAGIONRSM><![CDATA[{8}]]></REAGIONRSM><SUBRETURNTYPE><![CDATA[{9}]]></SUBRETURNTYPE><RETURNREASON><![CDATA[{10}]]></RETURNREASON></R></Table><Table Name=\"BIZ_RETURN_CS\"><R Index=\"1\"><INVOICE><![CDATA[]]></INVOICE><REJECTREASON><![CDATA[]]></REJECTREASON><RGA><![CDATA[]]></RGA><KE><![CDATA[]]></KE><REASONCODE><![CDATA[]]></REASONCODE></R></Table></Tables></Data>";
    }
}
