/*
 * Ibatis.Net for Data Mapper, and Generated by MyGeneration
 * 
 * NameSpace   : DMS.Model 
 * ClassName   : InventoryAdjustConsignment
 * Created Time: 2014/3/19 17:39:25
 *
 ******* Copyright (C) 2009/2010 - GrapeCity **********
 *
******************************************************/

using System;

namespace DMS.Model
{
    /// <summary>
    ///	InventoryAdjustConsignment
    /// </summary>
    [Serializable]
    public class InventoryAdjustConsignment : BaseModel
    {
        #region Private Members 5

        private Guid _id;
        private Guid _iah_id;
        private Guid _ltm_id;
        private decimal? _shippedqty;
        private Guid? _prh_id;
        private Guid? _dma_id;
        #endregion

        #region Default ( Empty ) Class Constuctor
        /// <summary>
        /// default constructor
        /// </summary>
        public InventoryAdjustConsignment()
        {
            _id = Guid.Empty;
            _iah_id = Guid.Empty;
            _ltm_id = Guid.Empty;
            _shippedqty = null;
            _prh_id = null;
            _dma_id = null;
        }
        #endregion // End of Default ( Empty ) Class Constuctor

        #region Public Properties

        /// <summary>
        /// IAC_ID
        /// </summary>		
        public Guid Id
        {
            get { return _id; }
            set { _id = value; }
        }

        /// <summary>
        /// IAC_IAH_ID
        /// </summary>		
        public Guid IahId
        {
            get { return _iah_id; }
            set { _iah_id = value; }
        }

        /// <summary>
        /// IAC_LTM_ID
        /// </summary>		
        public Guid LtmId
        {
            get { return _ltm_id; }
            set { _ltm_id = value; }
        }

        /// <summary>
        /// IAC_ShippedQty
        /// </summary>		
        public decimal? ShippedQty
        {
            get { return _shippedqty; }
            set { _shippedqty = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public Guid? PrhId
        {
            get { return _prh_id; }
            set { _prh_id = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public Guid? DmaId
        {
            get { return _dma_id; }
            set { _dma_id = value; }
        }
        #endregion





    }
}
