/*
 * Ibatis.Net for Data Mapper, and Generated by MyGeneration
 * 
 * NameSpace   : DMS.Model 
 * ClassName   : StocktakingLine
 * Created Time: 2010-6-3 11:32:13
 *
 ******* Copyright (C) 2009/2010 - GrapeCity **********
 *
******************************************************/

using System;

namespace DMS.Model
{
	/// <summary>
	///	StocktakingLine
	/// </summary>
	[Serializable]
	public class StocktakingLine : BaseModel
	{
		#region Private Members
		
		private Guid _id; 
		private Guid _sth_id; 
		private Guid _pma_id; 
		private double _quantity; 
		private int? _linenbr; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public StocktakingLine()
		{
			_id = new Guid(); 
			_sth_id = new Guid(); 
			_pma_id = new Guid(); 
			_quantity = new double(); 
			_linenbr = null;
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 主键
		/// </summary>		
		public Guid Id
		{
			get { return _id; }
			set { _id = value; }
		}
			
		/// <summary>
		/// 表头主键
		/// </summary>		
		public Guid SthId
		{
			get { return _sth_id; }
			set { _sth_id = value; }
		}
			
		/// <summary>
		/// 物料主键
		/// </summary>		
		public Guid PmaId
		{
			get { return _pma_id; }
			set { _pma_id = value; }
		}
			
		/// <summary>
		/// 数量
		/// </summary>		
		public double Quantity
		{
			get { return _quantity; }
			set { _quantity = value; }
		}
			
		/// <summary>
		/// 行号
		/// </summary>		
		public int? LineNbr
		{
			get { return _linenbr; }
			set { _linenbr = value; }
		}
			
		
	
		
		#endregion 
		
		
		
		
		
	}
}
