/*
 * Ibatis.Net for Data Mapper, and Generated by MyGeneration
 * 
 * NameSpace   : DMS.Model 
 * ClassName   : DealerHospital
 * Created Time: 2009-7-17 9:46:28
 *
 ******* Copyright (C) 2009/2010 - GrapeCity **********
 *
******************************************************/

using System;

namespace DMS.Model
{
    /// <summary>
    ///	HospitalList
    /// </summary>
    [Serializable]
    public class DealerHospital : BaseModel
    {
        #region Private Members

        private Guid? _dat_id;
        private Guid? _hos_id;
        private Guid? _id;
        private string _remark;
        private DateTime? _startdate;
        private DateTime? _enddate;
        #endregion

        #region Default ( Empty ) Class Constuctor
        /// <summary>
        /// default constructor
        /// </summary>
        public DealerHospital()
        {
            _dat_id = null;
            _hos_id = null;
            _id = null;
            _remark = null;
            _startdate = null;
            _enddate = null;
        }
        #endregion // End of Default ( Empty ) Class Constuctor

        #region Public Properties

        /// <summary>
        /// 授权行

        /// </summary>		
        public Guid? DatId
        {
            get { return _dat_id; }
            set { _dat_id = value; }
        }

        /// <summary>
        /// 医院主键
        /// </summary>		
        public Guid? HosId
        {
            get { return _hos_id; }
            set { _hos_id = value; }
        }

        /// <summary>
        /// 授权的医院

        /// </summary>		
        public Guid? Id
        {
            get { return _id; }
            set { _id = value; }
        }


        /// <summary>
        /// 备注信息，添加科室用
        /// </summary>		
        public string Remark
        {
            get { return _remark; }
            set
            {
                if (value != null && value.Length > 2000)
                    throw new ArgumentOutOfRangeException("Invalid value for Remark", value, value.ToString());

                _remark = value;
            }
        }

        /// <summary>
        /// 医院授权开始时间（用户销售单医院授权）
        /// </summary>		
        public DateTime? StartDate
        {
            get { return _startdate; }
            set { _startdate = value; }
        }

        /// <summary>
        /// 医院授权终止时间（用户销售单医院授权）
        /// </summary>		
        public DateTime? EndDate
        {
            get { return _enddate; }
            set { _enddate = value; }
        }
        #endregion





    }
}
