/*
 * Ibatis.Net for Data Mapper, and Generated by MyGeneration
 * 
 * NameSpace   : DMS.Model 
 * ClassName   : Virtualdc
 * Created Time: 2013/7/22 14:32:14
 *
 ******* Copyright (C) 2009/2010 - GrapeCity **********
 *
******************************************************/

using System;

namespace DMS.Model
{
	/// <summary>
	///	Virtualdc
	/// </summary>
	[Serializable]
	public class Virtualdc : BaseModel
	{
		#region Private Members 3
		
		private Guid _dma_id; 
		private Guid _bum_id; 
		private string _plant; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public Virtualdc()
		{
			_dma_id = Guid.Empty; 
			_bum_id = Guid.Empty; 
			_plant = null; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 经销商编号
		/// </summary>		
		public Guid DmaId
		{
			get { return _dma_id; }
			set { _dma_id = value; }
		}
			
		/// <summary>
		/// 产品线
		/// </summary>		
		public Guid BumId
		{
			get { return _bum_id; }
			set { _bum_id = value; }
		}
			
		/// <summary>
		/// BSC仓库号
		/// </summary>		
		public string Plant
		{
			get { return _plant; }
			set	
			{
				if( value!= null && value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Plant", value, value.ToString());
				
				_plant = value;
			}
		}
			
		
	
		
		#endregion 
		
		
		
		
		
	}
}
