DROP Procedure [dbo].[GC_Create_MWFAccount]
GO


CREATE Procedure [dbo].[GC_Create_MWFAccount]
AS
BEGIN
DECLARE @account NVARCHAR(100)
DECLARE @Name NVARCHAR(100)
DECLARE @Email NVARCHAR(100)
DECLARE @IDENTITY_ID uniqueidentifier
DECLARE @PRODUCT_CUR cursor;
	SET @PRODUCT_CUR=cursor for 
		SELECT account,isnull(Name,A.eName),Email FROM INTERFACE.MDM_EmployeeMaster  A
		WHERE NOT EXISTS (SELECT 1 FROM Lafite_IDENTITY B WHERE B.IDENTITY_CODE=A.account --AND IDENTITY_TYPE='User'
		) AND ISNULL(A.[Status],1)=1 and isnull(account,'')<>''
	OPEN @PRODUCT_CUR
	FETCH NEXT FROM @PRODUCT_CUR INTO @account,@Name,@Email
	WHILE @@FETCH_STATUS = 0        
		BEGIN
			SET @IDENTITY_ID=NEWID();
			INSERT INTO Lafite_IDENTITY 
						(Id,IDENTITY_CODE,LOWERED_IDENTITY_CODE,IDENTITY_NAME,
						BOOLEAN_FLAG,IDENTITY_TYPE,LastActivityDate,APP_ID,DELETE_FLAG,
						CREATE_USER,CREATE_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
					VALUES(@IDENTITY_ID,@account,@account,@Name,
						1,'User',getdate(),'4028931b0f0fc135010f0fc1356a0001',0,
						'00000000-0000-0000-0000-000000000000',GETDATE(),'00000000-0000-0000-0000-000000000000',GETDATE());
						
			INSERT INTO dbo.Lafite_Membership
			values(@IDENTITY_ID,'JwSWJpN51898uJjc7eriHZY/MSc=','1','rcmX5PF2DpzU5uP09ilGuA==',
			null,'','',null,null,'4028931b0f0fc135010f0fc1356a0001',1,0,GETDATE(),GETDATE(),'j3Mj1nPQ5V3HA5wvn6CvSvMq0qY=',GETDATE(),GETDATE(),0,GETDATE(),'0',GETDATE(),null)
				
		
		
	FETCH NEXT FROM @PRODUCT_CUR INTO @account,@Name,@Email
		END
	CLOSE @PRODUCT_CUR
	DEALLOCATE @PRODUCT_CUR ;
	

	UPDATE A SET  a.DELETE_FLAG=1, A.BOOLEAN_FLAG=0 FROM Lafite_IDENTITY A 
	WHERE EXISTS (SELECT 1 FROM INTERFACE.MDM_EmployeeMaster B WHERE a.IDENTITY_CODE=B.account AND B.[Status]=0)
	AND A.DELETE_FLAG=0 
	AND A.BOOLEAN_FLAG=1
	AND IDENTITY_TYPE='User'
	
END



GO


