DROP PROCEDURE [dbo].[Proc_DealerPurchaseForecastAdjustGet3MonthBP]
GO


CREATE PROCEDURE [dbo].[Proc_DealerPurchaseForecastAdjustGet3MonthBP]
(
	@UserId UNIQUEIDENTIFIER
)
AS
BEGIN
	DECLARE @SQL NVARCHAR(MAX);
	DECLARE @CURRENT_MONTH INT;
	
	SELECT @CURRENT_MONTH = MONTH(GETDATE())

	IF @CURRENT_MONTH>9
	BEGIN
		SET @CURRENT_MONTH=9
	END
	
	SET @SQL = 'SELECT 
		SUM(A.MONTH'+CONVERT(NVARCHAR,@CURRENT_MONTH+1)+') MonthlyBP1,
		SUM(A.MONTH'+CONVERT(NVARCHAR,@CURRENT_MONTH+2)+') MonthlyBP2,
		SUM(A.MONTH'+CONVERT(NVARCHAR,@CURRENT_MONTH+3)+') MonthlyBP3 
	FROM interface.RV_DealerQuota A,DealerMaster B,Lafite_IDENTITY C
	WHERE A.SAPID = B.DMA_SAP_Code AND B.DMA_ID = C.Corp_ID AND C.Id = '''+ CONVERT(NVARCHAR(100),@UserId) +'''
	AND a.Year = Year(getdate())'

	PRINT @SQL
	EXECUTE (@SQL)
END

GO


