--LP续约
--INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (N'2fb78cd6-366e-4558-a761-04937e0870f0', N'Renewal', N'LP', N'法人代表授权委托书', N'~/Upload/ContractElectronicAttachmentTemplate/LP/AppointmentRenewal/法人代表授权委托书.pdf', 0, 1, 9, N'UploadProxy')
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (N'2fb78cd6-366e-4558-a761-04937e0870f0', N'Renewal', N'LP', N'其它附件', N'~/Upload/ContractElectronicAttachmentTemplate/LP/AppointmentRenewal/其它附件.docx', 0, 1, 9, N'OtherAttachment')
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (N'8668a7a8-809d-4523-9658-0533950d8fd2', N'Renewal', N'LP', N'经销商协议_LP_附件三（返利评估表）', N'~/Upload/ContractElectronicAttachmentTemplate/LP/AppointmentRenewal/经销商协议_LP_附件三（返利评估表）.docx', 1, 1, 4, 'RebateAttachment')
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (N'e34878b4-6e25-4808-b985-0f34baee14d3', N'Renewal', N'LP', N'设备采购附件（仅适用于PUL,Uro设备,PION设备）', N'~/Upload/ContractElectronicAttachmentTemplate/LP/AppointmentRenewal/设备采购附件（仅适用于PUL,Uro设备,PION设备）.docx', 0, 1, 6, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (N'eb00b961-97c6-4f90-87ec-2ad20226d072', N'Renewal', N'LP', N'经销商协议_LP_附件一（Annex I— Dealer Quality Requirements）', N'~/Upload/ContractElectronicAttachmentTemplate/LP/AppointmentRenewal/经销商协议_LP_附件一（Annex I— Dealer Quality Requirements）.docx', 1, 1, 2, NULL)
--INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (N'3efa8a35-82f4-4b6d-9b4d-39ffa666cffa', N'Renewal', N'LP', N'提货授权委托书', N'~/Upload/ContractElectronicAttachmentTemplate/LP/AppointmentRenewal/提货授权委托书.pdf', 0, 1, 8, N'UploadGoods')
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (N'27a6cc7e-70fc-4939-94b4-495cfd00be9f', N'Renewal', N'LP', N'经销商协议_LP_附件二（指标清单）', N'~/Upload/ContractElectronicAttachmentTemplate/LP/AppointmentRenewal/经销商协议_LP_附件二（指标清单）.docx', 1, 1, 3, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (N'70d73027-86e1-4ca9-b3a2-9e7e44f06d30', N'Renewal', N'LP', N'产品仓储地址合规性声明', N'~/Upload/ContractElectronicAttachmentTemplate/LP/AppointmentRenewal/产品仓储地址合规性声明.docx', 0, 1, 10, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (N'4e16b4da-f843-4de2-82a0-b6e11236a9f8', N'Renewal', N'LP', N'数据质量保证函', N'~/Upload/ContractElectronicAttachmentTemplate/LP/AppointmentRenewal/数据质量保证函.docx', 0, 1, 7, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (N'6e4fad54-0775-4d1a-96a5-db256d47500d', N'Renewal', N'LP', N'经销商协议_LP', N'~/Upload/ContractElectronicAttachmentTemplate/LP/AppointmentRenewal/经销商协议_LP.docx', 1, 1, 1, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (N'cf50a81c-1555-4fd3-98a1-ece9070aeb3b', N'Renewal', N'LP', N'医疗器械质量保证协议-LP', N'~/Upload/ContractElectronicAttachmentTemplate/LP/AppointmentRenewal/医疗器械质量保证协议-LP.docx', 1, 1, 5, NULL)
--LP修改
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (N'06164ef2-f8be-4ec6-9a1c-f16fed5a52fa', N'Amendment', N'LP', N'经销商补充协议_LP', N'~/Upload/ContractElectronicAttachmentTemplate/LP/Amendment/经销商补充协议_LP.docx', 1, 1, 1, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (N'f82dbabb-3c47-480a-9973-228ee8a5ba4c', N'Amendment', N'LP', N'经销商补充协议_LP_附件二.', N'~/Upload/ContractElectronicAttachmentTemplate/LP/Amendment/经销商补充协议_LP_附件二.docx', 1, 1, 3, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (N'27ed5a86-a41c-4a46-a0af-c504a07501fb', N'Amendment', N'LP', N'经销商补充协议_LP_附件一', N'~/Upload/ContractElectronicAttachmentTemplate/LP/Amendment/经销商补充协议_LP_附件一.docx', 1, 1, 2, NULL)
--LP新经销商申请
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Appointment', N'LP', N'其它附件', N'~/Upload/ContractElectronicAttachmentTemplate/LP/AppointmentRenewal/其它附件.docx', 1, 1, 9, N'OtherAttachment')
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Appointment', N'LP', N'经销商协议_LP_附件三（返利评估表）', N'~/Upload/ContractElectronicAttachmentTemplate/LP/AppointmentRenewal/经销商协议_LP_附件三（返利评估表）.docx', 1, 1, 4, 'RebateAttachment')
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Appointment', N'LP', N'设备采购附件（仅适用于PUL,Uro设备,PION设备）', N'~/Upload/ContractElectronicAttachmentTemplate/LP/AppointmentRenewal/设备采购附件（仅适用于PUL,Uro设备,PION设备）.docx', 0, 1, 6, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Appointment', N'LP', N'经销商协议_LP_附件一（Annex I— Dealer Quality Requirements）', N'~/Upload/ContractElectronicAttachmentTemplate/LP/AppointmentRenewal/经销商协议_LP_附件一（Annex I— Dealer Quality Requirements）.docx', 1, 1, 2, NULL)
--INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Appointment', N'LP', N'提货授权委托书', N'~/Upload/ContractElectronicAttachmentTemplate/LP/AppointmentRenewal/提货授权委托书.pdf', 0, 1, 8, N'UploadGoods')
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Appointment', N'LP', N'经销商协议_LP_附件二（指标清单）', N'~/Upload/ContractElectronicAttachmentTemplate/LP/AppointmentRenewal/经销商协议_LP_附件二（指标清单）.docx', 1, 1, 3, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Appointment', N'LP', N'产品仓储地址合规性声明', N'~/Upload/ContractElectronicAttachmentTemplate/LP/AppointmentRenewal/产品仓储地址合规性声明.docx', 0, 1, 10, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Appointment', N'LP', N'数据质量保证函', N'~/Upload/ContractElectronicAttachmentTemplate/LP/AppointmentRenewal/数据质量保证函.docx', 0, 1, 7, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Appointment', N'LP', N'经销商协议_LP', N'~/Upload/ContractElectronicAttachmentTemplate/LP/AppointmentRenewal/经销商协议_LP.docx', 1, 1, 1, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Appointment', N'LP', N'医疗器械质量保证协议-LP', N'~/Upload/ContractElectronicAttachmentTemplate/LP/AppointmentRenewal/医疗器械质量保证协议-LP.docx', 1, 1, 5, NULL)
--T1续约
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Renewal', N'T1', N'经销商协议_T1', N'~/Upload/ContractElectronicAttachmentTemplate/T1/AppointmentRenewal/经销商协议_T1.docx', 1, 1, 1, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Renewal', N'T1', N'经销商协议_T1_附件一（Annex I— Dealer Quality Requirements）', N'~/Upload/ContractElectronicAttachmentTemplate/T1/AppointmentRenewal/经销商协议_T1_附件一（Annex I— Dealer Quality Requirements）.docx', 1, 1, 2, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Renewal', N'T1', N'经销商协议_T1 附件二（授权清单）', N'~/Upload/ContractElectronicAttachmentTemplate/T1/AppointmentRenewal/经销商协议_T1 附件二（授权清单）.docx', 1, 1, 3, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Renewal', N'T1', N'经销商协议_T1_附件三（指标清单）', N'~/Upload/ContractElectronicAttachmentTemplate/T1/AppointmentRenewal/经销商协议_T1_附件三（指标清单）.docx', 1, 1, 4, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Renewal', N'T1', N'设备采购附件（仅适用于PUL,Uro设备,PION设备）', N'~/Upload/ContractElectronicAttachmentTemplate/T1/AppointmentRenewal/设备采购附件（仅适用于PUL,Uro设备,PION设备）.docx', 0, 1, 5, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Renewal', N'T1', N'医疗器械质量保证协议-T1', N'~/Upload/ContractElectronicAttachmentTemplate/T1/AppointmentRenewal/医疗器械质量保证协议-T1.docx', 1, 1, 6, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Renewal', N'T1', N'其它附件', N'~/Upload/ContractElectronicAttachmentTemplate/T1/AppointmentRenewal/其它附件.docx', 1, 1, 7, 'OtherAttachment')
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Renewal', N'T1', N'数据质量保证函', N'~/Upload/ContractElectronicAttachmentTemplate/T1/AppointmentRenewal/数据质量保证函.docx', 1, 1, 8, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Renewal', N'T1', N'提货授权委托书', N'~/Upload/ContractElectronicAttachmentTemplate/T1/AppointmentRenewal/提货授权委托书.docx', 1, 1, 9, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Renewal', N'T1', N'产品仓储地址合规性声明', N'~/Upload/ContractElectronicAttachmentTemplate/T1/AppointmentRenewal/产品仓储地址合规性声明.docx', 0, 1, 10, NULL)

--T1新申请
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Appointment', N'T1', N'经销商协议_T1', N'~/Upload/ContractElectronicAttachmentTemplate/T1/AppointmentRenewal/经销商协议_T1.docx', 1, 1, 1, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Appointment', N'T1', N'经销商协议_T1_附件一（Annex I— Dealer Quality Requirements）', N'~/Upload/ContractElectronicAttachmentTemplate/T1/AppointmentRenewal/经销商协议_T1_附件一（Annex I— Dealer Quality Requirements）.docx', 1, 1, 2, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Appointment', N'T1', N'经销商协议_T1 附件二（授权清单）', N'~/Upload/ContractElectronicAttachmentTemplate/T1/AppointmentRenewal/经销商协议_T1 附件二（授权清单）.docx', 1, 1, 3, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Appointment', N'T1', N'经销商协议_T1_附件三（指标清单）', N'~/Upload/ContractElectronicAttachmentTemplate/T1/AppointmentRenewal/经销商协议_T1_附件三（指标清单）.docx', 1, 1, 4, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Appointment', N'T1', N'设备采购附件（仅适用于PUL,Uro设备,PION设备）', N'~/Upload/ContractElectronicAttachmentTemplate/T1/AppointmentRenewal/设备采购附件（仅适用于PUL,Uro设备,PION设备）.docx', 0, 1, 5, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Appointment', N'T1', N'医疗器械质量保证协议-T1', N'~/Upload/ContractElectronicAttachmentTemplate/T1/AppointmentRenewal/医疗器械质量保证协议-T1.docx', 1, 1, 6, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Appointment', N'T1', N'其它附件', N'~/Upload/ContractElectronicAttachmentTemplate/T1/AppointmentRenewal/其它附件.docx', 1, 1, 7, 'OtherAttachment')
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Appointment', N'T1', N'数据质量保证函', N'~/Upload/ContractElectronicAttachmentTemplate/T1/AppointmentRenewal/数据质量保证函.docx', 1, 1, 8, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Appointment', N'T1', N'提货授权委托书', N'~/Upload/ContractElectronicAttachmentTemplate/T1/AppointmentRenewal/提货授权委托书.docx', 1, 1, 9, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Appointment', N'T1', N'产品仓储地址合规性声明', N'~/Upload/ContractElectronicAttachmentTemplate/T1/AppointmentRenewal/产品仓储地址合规性声明.docx', 0, 1, 10, NULL)

--T1修改

INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Amendment', N'T1', N'经销商补充协议_T1', N'~/Upload/ContractElectronicAttachmentTemplate/T1/Amendment/经销商补充协议_T1.docx', 1, 1, 1, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Amendment', N'T1', N'经销商协议_T1 附件二（授权清单）', N'~/Upload/ContractElectronicAttachmentTemplate/T1/Amendment/经销商协议_T1 附件二（授权清单）.docx', 1, 1, 2, NULL)
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Amendment', N'T1', N'经销商协议_T1_附件三（指标清单）', N'~/Upload/ContractElectronicAttachmentTemplate/T1/Amendment/经销商协议_T1_附件三（指标清单）.docx', 1, 1, 3, NULL)


--T1终止
INSERT [Contract].[ExportTemplate] ([TemplateId], [ContractType], [DealerType], [TemplateName], [TemplateFile], [IsRequired], [IsActive], [DisplayOrder], [TemplateType]) VALUES (NEWID(), N'Termination', N'T1', N'经销商终止协议_T1', N'~/Upload/ContractElectronicAttachmentTemplate/T1/Termination/经销商终止协议_T1.docx', 1, 1, 1, NULL)

