INSERT INTO Lafite_DICTTYPE(DICT_TYPE,DICT_TYPE_NAME,DESCRIPTION,SORT_COL,APP_ID,SYS_FLAG)
VALUES('ContractElectronic','电子合同状态','电子合同状态','0','4028931b0f0fc135010f0fc1356a0001','1')
DELETE Lafite_DICT WHERE DICT_TYPE='ContractElectronic'


INSERT INTO Lafite_DICT(Id,PID,DICT_LEVEL,DICT_TYPE,DICT_KEY,VALUE1,APP_ID,SORT_COL,DELETE_FLAG,CREATE_USER,CREATE_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
VALUES(NEWID(),'ContractElectronic','1','ContractElectronic','Draft','草稿','4028931b0f0fc135010f0fc1356a0001',0,0,'System',GETDATE(),'System',GETDATE())

--INSERT INTO Lafite_DICT(Id,PID,DICT_LEVEL,DICT_TYPE,DICT_KEY,VALUE1,APP_ID,SORT_COL,DELETE_FLAG,CREATE_USER,CREATE_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
--VALUES(NEWID(),'ContractElectronic','1','ContractElectronic','InApprova','签章中','4028931b0f0fc135010f0fc1356a0001',1,0,'System',GETDATE(),'System',GETDATE())

INSERT INTO Lafite_DICT(Id,PID,DICT_LEVEL,DICT_TYPE,DICT_KEY,VALUE1,APP_ID,SORT_COL,DELETE_FLAG,CREATE_USER,CREATE_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
VALUES(NEWID(),'ContractElectronic','1','ContractElectronic','WaitBscSign','待波科签章','4028931b0f0fc135010f0fc1356a0001',1,0,'System',GETDATE(),'System',GETDATE())

INSERT INTO Lafite_DICT(Id,PID,DICT_LEVEL,DICT_TYPE,DICT_KEY,VALUE1,APP_ID,SORT_COL,DELETE_FLAG,CREATE_USER,CREATE_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
VALUES(NEWID(),'ContractElectronic','1','ContractElectronic','WaitDealerSign','待经销商签章','4028931b0f0fc135010f0fc1356a0001',1,0,'System',GETDATE(),'System',GETDATE())


--INSERT INTO Lafite_DICT(Id,PID,DICT_LEVEL,DICT_TYPE,DICT_KEY,VALUE1,APP_ID,SORT_COL,DELETE_FLAG,CREATE_USER,CREATE_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
--VALUES(NEWID(),'ContractElectronic','1','ContractElectronic','Submitted','待签章','4028931b0f0fc135010f0fc1356a0001',2,0,'System',GETDATE(),'System',GETDATE())

INSERT INTO Lafite_DICT(Id,PID,DICT_LEVEL,DICT_TYPE,DICT_KEY,VALUE1,APP_ID,SORT_COL,DELETE_FLAG,CREATE_USER,CREATE_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
VALUES(NEWID(),'ContractElectronic','1','ContractElectronic','Complete','签章完成','4028931b0f0fc135010f0fc1356a0001',3,0,'System',GETDATE(),'System',GETDATE())

INSERT INTO Lafite_DICT(Id,PID,DICT_LEVEL,DICT_TYPE,DICT_KEY,VALUE1,APP_ID,SORT_COL,DELETE_FLAG,CREATE_USER,CREATE_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
VALUES(NEWID(),'ContractElectronic','1','ContractElectronic','BscAbandonment','波科作废','4028931b0f0fc135010f0fc1356a0001',4,0,'System',GETDATE(),'System',GETDATE())

INSERT INTO Lafite_DICT(Id,PID,DICT_LEVEL,DICT_TYPE,DICT_KEY,VALUE1,APP_ID,SORT_COL,DELETE_FLAG,CREATE_USER,CREATE_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
VALUES(NEWID(),'ContractElectronic','1','ContractElectronic','Cancelled','撤销签章','4028931b0f0fc135010f0fc1356a0001',5,0,'System',GETDATE(),'System',GETDATE())

INSERT INTO Lafite_DICT(Id,PID,DICT_LEVEL,DICT_TYPE,DICT_KEY,VALUE1,APP_ID,SORT_COL,DELETE_FLAG,CREATE_USER,CREATE_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
VALUES(NEWID(),'ContractElectronic','1','ContractElectronic','WaitDealerAbandonment','待经销商作废','4028931b0f0fc135010f0fc1356a0001',5,0,'System',GETDATE(),'System',GETDATE())

INSERT INTO Lafite_DICT(Id,PID,DICT_LEVEL,DICT_TYPE,DICT_KEY,VALUE1,APP_ID,SORT_COL,DELETE_FLAG,CREATE_USER,CREATE_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
VALUES(NEWID(),'ContractElectronic','1','ContractElectronic','Abandonment','已作废','4028931b0f0fc135010f0fc1356a0001',5,0,'System',GETDATE(),'System',GETDATE())
SELECT DICT_KEY as [Key],VALUE1 as Value FROM Lafite_DICT WHERE DICT_TYPE=''