/*
 * Ibatis.Net for Data Mapper, and Generated by MyGeneration
 * 
 * NameSpace   : DMS.Model 
 * ClassName   : DpRight
 * Created Time: 2013/5/29 13:16:17
 *
 ******* Copyright (C) 2009/2010 - GrapeCity **********
 *
******************************************************/

using System;

namespace DMS.Model
{
	/// <summary>
	///	DpRight
	/// </summary>
	[Serializable]
	public class DpRight
	{
		#region Private Members 16
		
		private Guid _id; 
		private Guid? _modleid;
        private Guid? _roleid; 
		private bool? _isread; 
		private bool? _iswrite; 
		private bool? _iscreate; 
		private bool? _isdelete; 
		private bool? _isimport; 
		private bool? _isoutport; 
		private string _createby; 
		private DateTime? _createdate; 
		private string _modifyby; 
		private DateTime? _modifydate; 
		private bool? _isaction; 
		private string _deleteby; 
		private DateTime? _deletedate; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public DpRight()
		{
			_id = Guid.Empty; 
			_modleid = null;
			_roleid = null;
			_isread = null;
			_iswrite = null;
			_iscreate = null;
			_isdelete = null;
			_isimport = null;
			_isoutport = null;
			_createby = null; 
			_createdate = null;
			_modifyby = null; 
			_modifydate = null;
			_isaction = null;
			_deleteby = null; 
			_deletedate = null;
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public Guid Id
		{
			get { return _id; }
			set { _id = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public Guid? Modleid
		{
			get { return _modleid; }
			set { _modleid = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
        public Guid? Roleid
		{
			get { return _roleid; }
			set { _roleid = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public bool? IsRead
		{
			get { return _isread; }
			set { _isread = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public bool? IsWrite
		{
			get { return _iswrite; }
			set { _iswrite = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public bool? IsCreate
		{
			get { return _iscreate; }
			set { _iscreate = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public bool? IsDelete
		{
			get { return _isdelete; }
			set { _isdelete = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public bool? IsImport
		{
			get { return _isimport; }
			set { _isimport = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public bool? IsOutport
		{
			get { return _isoutport; }
			set { _isoutport = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string CreateBy
		{
			get { return _createby; }
			set	
			{
				if( value!= null && value.Length > 200)
					throw new ArgumentOutOfRangeException("Invalid value for CreateBy", value, value.ToString());
				
				_createby = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? CreateDate
		{
			get { return _createdate; }
			set { _createdate = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string ModifyBy
		{
			get { return _modifyby; }
			set	
			{
				if( value!= null && value.Length > 200)
					throw new ArgumentOutOfRangeException("Invalid value for ModifyBy", value, value.ToString());
				
				_modifyby = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? ModifyDate
		{
			get { return _modifydate; }
			set { _modifydate = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public bool? IsAction
		{
			get { return _isaction; }
			set { _isaction = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string DeleteBy
		{
			get { return _deleteby; }
			set	
			{
				if( value!= null && value.Length > 200)
					throw new ArgumentOutOfRangeException("Invalid value for DeleteBy", value, value.ToString());
				
				_deleteby = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? DeleteDate
		{
			get { return _deletedate; }
			set { _deletedate = value; }
		}
			
		
	
		
		#endregion 
		
		
		
		
		
	}
}
