DROP VIEW [interface].[V_I_EW_QACRMDealerComplain]
GO

CREATE VIEW [interface].[V_I_EW_QACRMDealerComplain]
AS
SELECT DC_ComplainNbr AS DMSBSCCode,       
       DC_Status,       
       EID,
       Model,
       Serial,
       Lot,
       [PI],
       IAN,
       CompletedName,
       CompletedTitle,
       NonBostonName,
       NonBostonCompany,
       NonBostonAddress,
       NonBostonCity,
       NonBostonCountry,
       Convert(datetime,NULLIF(DateEvent,N'')) AS DateEvent,
       Convert(datetime,NULLIF(DateBSC,N'')) AS DateBSC,
       Convert(datetime,NULLIF(DateDealer,N'')) AS DateDealer,
       EventCountry,
       OtherCountry,
       NeedSupport,
       PatientName,
       PatientNum,
       PatientSex,
       PatientSexInvalid,
       Convert(datetime,NULLIF(PatientBirth,N'')) AS PatientBirth,
       PatientBirthInvalid,
       PatientWeight,
       PatientWeightInvalid,
       PhysicianName,
       PhysicianHospital,
       PhysicianTitle,
       PhysicianAddress,
       PhysicianCity,
       PhysicianZipcode,
       PhysicianCountry,
       PatientStatus,
       Convert(datetime,NULLIF(DeathDate,N'')) AS DeathDate,
       DeathTime,
       DeathCause,
       Witnessed,
       RelatedBSC,
       ReasonsForProduct,
       Returned,
       ReturnedDay,
       AnalysisReport,
       RequestPhysicianName,
       Warranty,
       Pulse,
       Pulsebeats,
       Leads,
       LeadsFracture,
       LeadsIssue,
       LeadsDislodgement,
       LeadsMeasurements,
       LeadsThresholds,
       LeadsBeats,
       LeadsNoise,
       LeadsLoss,
       Clinical,
       ClinicalPerforation,
       ClinicalBeats,
       PulseModel,
       PulseSerial,
       Convert(datetime,NULLIF(PulseImplant,N'')) AS PulseImplant,
       Leads1Model,
       Leads1Serial,
       Convert(datetime,NULLIF(Leads1Implant,N'')) AS Leads1Implant,
       Leads1Position,
       Leads2Model,
       Leads2Serial,
       Convert(datetime,NULLIF(Leads2Implant,N'')) AS Leads2Implant,
       Leads2Position,
       Leads3Model,
       Leads3Serial,
       Convert(datetime,NULLIF(Leads3Implant,N'')) AS Leads3Implant,
       Leads3Position,
       AccessoryModel,
       AccessorySerial,
       Convert(datetime,NULLIF(AccessoryImplant,N'')) AS AccessoryImplant,
       AccessoryLot,
       Convert(datetime,NULLIF(ExplantDate,N'')) AS ExplantDate,
       RemainsService,
       RemovedService,
       Replace1Model,
       Replace1Serial,
       Convert(datetime,NULLIF(Replace1Implant,N'')) AS Replace1Implant,
       Replace2Model,
       Replace2Serial,
       Convert(datetime,NULLIF(Replace2Implant,N'')) AS Replace2Implant,
       Replace3Model,
       Replace3Serial,
       Convert(datetime,NULLIF(Replace3Implant,N'')) AS Replace3Implant,
       Replace4Model,
       Replace4Serial,
       Convert(datetime,NULLIF(Replace4Implant,N'')) AS Replace4Implant,
       Replace5Model,
       Replace5Serial,
       Convert(datetime,NULLIF(Replace5Implant,N'')) AS Replace5Implant,
       ProductExpDetail,
       CustomerComment,
       DN,
       CarrierNumber,
       ProductType,
       ReturnType,
       case when DM.DMA_DealerType='T1' then '2' else '1' end AS ISPLATFORM,
       BSCSoldToAccount,
       Case when DM.DMA_DealerType='T2' then Parent_SAP_Code else DMA_SAP_Code end AS CRMSoldToName,
       BSCSoldToCity AS CRMSoldToCity,
       Case when DM.DMA_DealerType='T2' then DMA_SAP_Code else '' end AS SubSoldToName,
       SubSoldToCity,
       DistributorCustomer,
       DistributorCity,
       IsForBSCProduct ,
       WHMID,
       case when WHMID = '00000000-0000-0000-0000-000000000000' then '销售到医院' else (select whm_name from Warehouse where WHM_ID = WHMID) end as WHM_Name
  FROM DealerComplainCRM(nolock)  
  inner join (select t1.DMA_ID,t1.DMA_SAP_Code,t1.DMA_DealerType,t2.DMA_SAP_Code As Parent_SAP_Code from dealermaster t1(nolock),dealermaster t2(nolock) where t1.DMA_Parent_DMA_ID = t2.DMA_ID) AS DM on (DealerComplainCRM.DC_CorpId = DM.DMA_ID)
 WHERE DC_Status = 'Submit'
GO


